services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/conf:/etc/mysql/conf.d  # 挂在数据库配置
      - ../mysql/data:/var/lib/mysql  # 挂在数据库数据
    networks:
      - network
    healthcheck:
      test: mysqladmin ping -h localhost -u ${DB_USER} -p${DB_PASSWORD}
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build:
      context: ./Server/  # 上下文路徑
      dockerfile: ./Dockerfile
    image: webserver
    container_name: webserver
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_ENGINE: ${DB_ENGINE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ../media/:/Server/media/  # 挂在多媒體目錄
    networks:
      - network
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Client/nginx.conf:/etc/nginx/nginx.conf  # 挂在nginx配置文件
      - ./Client/:/usr/share/nginx/html/  # 挂在前端項目
      - ../media/:/usr/share/nginx/html/media/  # 挂在多媒體目錄
    networks:
      - network
    depends_on:
      - webserver

networks:
  network: {}
