# Generated by Django 4.2.2 on 2023-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='user', to='users.role', verbose_name='角色'),
        ),
    ]
