# Generated by Django 4.2.2 on 2023-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='api',
            field=models.ManyToManyField(blank=True, related_name='role', to='users.api', verbose_name='權限'),
        ),
    ]
