# Generated by Django 4.2.2 on 2023-11-29 01:40

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('title', models.CharField(max_length=32, verbose_name='標題')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('image', models.ImageField(upload_to=blogs.models.get_image_path, verbose_name='圖片')),
            ],
            options={
                'verbose_name': '圖片表',
                'verbose_name_plural': '圖片表',
                'db_table': 'image',
            },
        ),
    ]
