# Generated by Django 4.2.2 on 2023-08-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
