# Generated by Django 4.2.2 on 2023-08-10 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_alter_blog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('author', 'title')},
        ),
    ]
