# Generated by Django 4.2.2 on 2023-11-02 01:49

import blogs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_alter_blog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('image', models.ImageField(upload_to=blogs.models.get_image_path, verbose_name='圖片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog', verbose_name='博客')),
            ],
            options={
                'verbose_name': '圖片表',
                'verbose_name_plural': '圖片表',
                'db_table': 'image',
            },
        ),
    ]
